# Generated by Django 5.1.2 on 2024-11-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='audio_url',
            field=models.URLField(null=True),
        ),
    ]
